import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
const backGround=Color.fromRGBO(238, 240, 249, 1);
const red=Color.fromRGBO(246,20, 20, 1);
const white=Colors.white;
const orangeLight=Color.fromRGBO(255,162, 0, 1);
const yellow=Color.fromRGBO(255,193, 7, 1);
const orangeDark=Color.fromRGBO(255,85, 0, 1);
const blue=Color.fromRGBO(45,95,255, 1);
const green=Color.fromRGBO(0,198,105, 1);
const black=Color.fromRGBO(0,0,0,1);
const textColor=Color.fromRGBO(38,50,91,1);
const double paddinglarg=33;
const double fonttitel=18;
const double fontSubTitel=16;
const double fontbigger=36;
const double fontxlarg=30;
const double fontlarge=20;
const double fontsmaller=12;
const kMainColor = Color(0xFF69A03A);
const kLogo = 'assets/images/logo.png';
const kName = 'name';
const kAddress = 'address';
const kEmail = 'email';
const kPhoneNumber = 'phone number';
